import { UserButton } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import toast from "react-hot-toast";

import { api } from "~/utils/api";

export default function Home() {
  const [input, setInput] = useState("");

  const cash = api.cash.get.useQuery();

  if (cash.isLoading) return <div>Loading...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center items-center">

        {/* cash balance and account management */}
        <div className="flex items-center border w-full md:max-w-2xl p-4">
          <div className="float-left">
            <UserButton afterSignOutUrl="/" />
          </div>
          <div className="flex-grow"></div>
          <div className="float-right text-right">
            <div>
              Hi {cash.data?.name ?? "there"}!
            </div>
            <div>
              Your cash is ${cash.data?.amount}
            </div>
          </div>
        </div>
        {/* END cash balance and account management */}


        {/* class card */}
        <div className="flex items-center border border w-full md:max-w-2xl p-4">
          <div className="float-left">
            Class name goes here
          </div>
          <div className="flex-grow"></div>
          <div className="float-right">
            <div className="text-right">
              Bank Balance: -$10 (dummy)
            </div>
            <Link href="/withdraw">
              <button
                className="bg-slate-400 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
              >Withdraw</button>
            </Link>
            <Link className="float-right" href="/deposit">
              <button
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
              >Deposit</button>
            </Link>
          </div>
        </div>
        <div className="md:max-w-xl p-4 w-10/12 border-x border-b">
          Recent transactions go here
        </div>
        {/* END class card */}

      </main >
    </>
  );
}
